### PR TITLE
Merge develop to main

### PR DESCRIPTION
**Pull request by Antoine-973**

### CODE REVIEW

**Comment by Antoine-973** [comment]
TROP COOOL

**Comment by Antoine-973** [comment]
J'adore ton code @maximecarl 👍🏻

**Comment by maximecarl** [comment]
ok for me, I really like this projet
#esgi #lovecoding #yessaaaaaay

**Comment by Antoine-973** [comment]
EN ROUTE !

**Review by maximecarl — APPROVED** [review]

**Pull request merged**
